### ISSUE TITLE
add link to the docs?

### ISSUE THREAD

**Issue by maelle** [openjournals/buffy#21]
i.e. https://buffy.readthedocs.io/en/latest/

**Comment by xuanxu** [comment]
You mean in the README? there's this banner:

![Captura de pantalla 2021-01-18 a las 17 38 22](https://user-images.githubusercontent.com/6528/104942014-271b0680-59b4-11eb-81e3-41ff09cc1e75.png)

Do you think a simple link would me more intuitive?

**Comment by maelle** [comment]
I was expecting it as repo URL near the description " Editorial bots generator ". :-)

**Comment by xuanxu** [comment]
Done!
