### ISSUE TITLE
Workers need to have a unique tmp directory

### ISSUE THREAD

**Issue by arfon** [openjournals/buffy#7]
Currently all workers (in Whedon) share a temporary file space (cloning Git repos to `/tmp/#{issue_id}`) which means that when multiple workers are running in parallel there can be weird bugs where one worker will delete the directory when cleaning up after itself.

To address this we should make sure that we namespace the tmp directories in some way. One approach could be to use the Sidekiq process ID within the worker to make sure each job is working in an isolated namespace.

**Comment by arfon** [comment]
Just an FYI @xuanxu, over in openjournals/whedon-api#114 I've got a version of this implemented (and running in production).

**Comment by xuanxu** [comment]
Done, the BuffyWorker sets its [path](https://github.com/openjournals/buffy/blob/master/app/workers/buffy_worker.rb#L30-L32) to a job_id folder in tmp
