### ISSUE TITLE
Commands at any point in comment / multiple commands?

### ISSUE THREAD

**Issue by sneakers-the-rat** [openjournals/buffy#98]
Hello! 

new editor here, I made what is probably a common error on my first go with editorialbot, putting a command at the end of a comment: https://github.com/openjournals/joss-reviews/issues/6193#issuecomment-1951642394

and checking the docs i see 
> EditorialBot commands must be placed in the first line of a comment. Other text can be added after the first line with the command. Multiple commands are not allowed in the same comment, only the first one will be interpreted.

Is that desired behavior?

I see that each responder is called for each message: https://github.com/openjournals/buffy/blob/7cf484fac3ac99c5600d301ad57f3a70e9428c8d/app/lib/responder_registry.rb#L22

and it seems like the primary filters are a match in `event_action` and `event_regex`: https://github.com/openjournals/buffy/blob/7cf484fac3ac99c5600d301ad57f3a70e9428c8d/app/lib/responder.rb#L60

so in my case that would be this: https://github.com/openjournals/buffy/blob/7cf484fac3ac99c5600d301ad57f3a70e9428c8d/app/responders/assign_editor_responder.rb#L9

where the "command needs to be at the beginning of the message" is just encoded by that `\A`. 

It seems like an alternative strategy might be to just use `^`, split each message on newlines, and do the call that way? So then the syntax is "commands need to be at the start of a line" but multiple commands would be allowed in a single comment, executed in order. One could split on `@#{bot_name}` to allow commands anywhere in a comment as well, but that might get a little chaotic.

but like i said not sure if one command at beginning of message is desired behavior. would be happy to PR.

**Comment by xuanxu** [comment]
Hi @sneakers-the-rat
Yeah, the current behaviour is desired. If we allow bot commands in any line, that can cause problems with commands in the middle of long commets and commands being invoked unexpectedly if found in quotes or code, as this would be valid commands:
```
a code fragment with a
@editorialbot command in it
```

> quote replying other comment with a
@editorialbot command here

(we could add validations for these cases but that would make the checks and regex more complex and prone to errors)

For clarity sake we decided to allow just one bot command per comment and have it really visible for everyone in the first line.

**Comment by sneakers-the-rat** [comment]
alright! question answered

**Comment by arfon** [comment]
Good question @sneakers-the-rat but hopefully this makes sense!
